<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <defaultLandingTab>standard-home</defaultLandingTab>
    <label>Recruiting</label>
    <tab>standard-Chatter</tab>
    <tab>Position__c</tab>
    <tab>standard-Dashboard</tab>
    <tab>standard-Document</tab>
    <tab>standard-report</tab>
    <tab>Candidate__c</tab>
    <tab>Interviewer__c</tab>
    <tab>Job_Application__c</tab>
    <tab>Job_Posting_Site__c</tab>
    <tab>Review__c</tab>
    <tab>Offer__c</tab>
    <tab>Salary__c</tab>
    <tab>Book__c</tab>
    <tab>Accounttest__c</tab>
    <tab>Order__c</tab>
    <tab>Zip_Code__c</tab>
    <tab>Position_Approval_Matrix__c</tab>
    <tab>Candidate_Snapshot__c</tab>
    <tab>fv__c</tab>
    <tab>Job_Posting__c</tab>
    <tab>Employee__c</tab>
    <tab>Customer__c</tab>
    <tab>JnJTask__c</tab>
    <tab>Student__c</tab>
    <tab>yahoo</tab>
    <tab>UnivStudent__c</tab>
    <tab>UnivMarks__c</tab>
    <tab>UnivSubject__c</tab>
    <tab>Device__c</tab>
    <tab>Hiring_Manager__c</tab>
    <tab>Rediff</tab>
    <tab>Facebook</tab>
    <tab>Company__c</tab>
    <tab>Dependent__c</tab>
    <tab>Objective__c</tab>
    <tab>third</tab>
    <tab>Expense__c</tab>
</CustomApplication>
