<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <defaultLandingTab>standard-home</defaultLandingTab>
    <detailPageRefreshMethod>none</detailPageRefreshMethod>
    <enableKeyboardShortcuts>false</enableKeyboardShortcuts>
    <enableMultiMonitorComponents>false</enableMultiMonitorComponents>
    <isServiceCloudConsole>true</isServiceCloudConsole>
    <keyboardShortcuts>
        <defaultShortcut>
            <action>FOCUS_CONSOLE</action>
            <active>true</active>
            <keyCommand>ESC</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_NAVIGATOR_TAB</action>
            <active>true</active>
            <keyCommand>V</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_DETAIL_VIEW</action>
            <active>true</active>
            <keyCommand>SHIFT+S</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_PRIMARY_TAB_PANEL</action>
            <active>true</active>
            <keyCommand>P</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_SUBTAB_PANEL</action>
            <active>true</active>
            <keyCommand>S</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_LIST_VIEW</action>
            <active>true</active>
            <keyCommand>N</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_FIRST_LIST_VIEW</action>
            <active>true</active>
            <keyCommand>SHIFT+F</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_SEARCH_INPUT</action>
            <active>true</active>
            <keyCommand>R</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>MOVE_LEFT</action>
            <active>true</active>
            <keyCommand>LEFT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>MOVE_RIGHT</action>
            <active>true</active>
            <keyCommand>RIGHT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>UP_ARROW</action>
            <active>true</active>
            <keyCommand>UP ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>DOWN_ARROW</action>
            <active>true</active>
            <keyCommand>DOWN ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>OPEN_TAB_SCROLLER_MENU</action>
            <active>true</active>
            <keyCommand>D</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>OPEN_TAB</action>
            <active>true</active>
            <keyCommand>T</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>CLOSE_TAB</action>
            <active>true</active>
            <keyCommand>C</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>REFRESH_TAB</action>
            <active>false</active>
            <keyCommand>SHIFT+R</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>ENTER</action>
            <active>true</active>
            <keyCommand>ENTER</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>EDIT</action>
            <active>true</active>
            <keyCommand>E</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>SAVE</action>
            <active>true</active>
            <keyCommand>CTRL+S</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>CONSOLE_LINK_DIALOG</action>
            <active>false</active>
            <keyCommand>U</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>HOTKEYS_PANEL</action>
            <active>false</active>
            <keyCommand>SHIFT+K</keyCommand>
        </defaultShortcut>
    </keyboardShortcuts>
    <listPlacement>
        <location>full</location>
    </listPlacement>
    <listRefreshMethod>none</listRefreshMethod>
    <saveUserSessions>false</saveUserSessions>
    <tab>standard-Account</tab>
    <tab>standard-Contact</tab>
    <tab>standard-Case</tab>
    <tab>standard-Opportunity</tab>
    <tab>standard-Lead</tab>
    <tab>standard-Knowledge</tab>
    <tab>Offer__c</tab>
    <tab>Salary__c</tab>
    <tab>Book__c</tab>
    <tab>Accounttest__c</tab>
    <tab>Order__c</tab>
    <tab>Candidate_Snapshot__c</tab>
    <tab>fv__c</tab>
    <tab>Job_Posting__c</tab>
    <tab>Employee__c</tab>
    <tab>Customer__c</tab>
    <tab>JnJTask__c</tab>
    <tab>Student__c</tab>
    <tab>Customer_lead__c</tab>
    <tab>yahoo</tab>
    <tab>UnivStudent__c</tab>
    <tab>UnivMarks__c</tab>
    <tab>UnivSubject__c</tab>
    <tab>Device__c</tab>
    <tab>Hiring_Manager__c</tab>
    <tab>Rediff</tab>
    <tab>Rating__c</tab>
    <tab>Facebook</tab>
    <tab>Company__c</tab>
    <tab>Dependent__c</tab>
    <tab>Objective__c</tab>
    <tab>third</tab>
    <tab>Expense__c</tab>
    <workspaceMappings>
        <mapping>
            <tab>Rediff</tab>
        </mapping>
        <mapping>
            <tab>Offer__c</tab>
        </mapping>
        <mapping>
            <fieldName>AccountId</fieldName>
            <tab>standard-Opportunity</tab>
        </mapping>
        <mapping>
            <tab>Expense__c</tab>
        </mapping>
        <mapping>
            <fieldName>AccountId</fieldName>
            <tab>standard-Case</tab>
        </mapping>
        <mapping>
            <tab>Job_Posting__c</tab>
        </mapping>
        <mapping>
            <tab>Device__c</tab>
        </mapping>
        <mapping>
            <fieldName>AccountId</fieldName>
            <tab>standard-Contact</tab>
        </mapping>
        <mapping>
            <tab>Hiring_Manager__c</tab>
        </mapping>
        <mapping>
            <tab>Company__c</tab>
        </mapping>
        <mapping>
            <tab>Customer__c</tab>
        </mapping>
        <mapping>
            <tab>Employee__c</tab>
        </mapping>
        <mapping>
            <tab>Customer_lead__c</tab>
        </mapping>
        <mapping>
            <tab>Objective__c</tab>
        </mapping>
        <mapping>
            <tab>Rating__c</tab>
        </mapping>
        <mapping>
            <tab>yahoo</tab>
        </mapping>
        <mapping>
            <tab>JnJTask__c</tab>
        </mapping>
        <mapping>
            <tab>UnivSubject__c</tab>
        </mapping>
        <mapping>
            <tab>standard-Lead</tab>
        </mapping>
        <mapping>
            <tab>Facebook</tab>
        </mapping>
        <mapping>
            <tab>Candidate_Snapshot__c</tab>
        </mapping>
        <mapping>
            <tab>Order__c</tab>
        </mapping>
        <mapping>
            <tab>third</tab>
        </mapping>
        <mapping>
            <tab>Accounttest__c</tab>
        </mapping>
        <mapping>
            <tab>Student__c</tab>
        </mapping>
        <mapping>
            <tab>Dependent__c</tab>
        </mapping>
        <mapping>
            <tab>Salary__c</tab>
        </mapping>
        <mapping>
            <tab>Book__c</tab>
        </mapping>
        <mapping>
            <tab>fv__c</tab>
        </mapping>
        <mapping>
            <tab>standard-Knowledge</tab>
        </mapping>
        <mapping>
            <tab>standard-Account</tab>
        </mapping>
        <mapping>
            <tab>UnivStudent__c</tab>
        </mapping>
        <mapping>
            <tab>UnivMarks__c</tab>
        </mapping>
    </workspaceMappings>
</CustomApplication>
